// <auto-generated />
namespace Kitaprazzi.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Kitaprazzi_V3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Kitaprazzi_V3));
        
        string IMigrationMetadata.Id
        {
            get { return "201806231227309_Kitaprazzi_V3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
