// <auto-generated />
namespace Kitaprazzi.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class kitaprazzi_V4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(kitaprazzi_V4));
        
        string IMigrationMetadata.Id
        {
            get { return "201807101230099_kitaprazzi_V4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
