// <auto-generated />
namespace Kitaprazzi.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class missingTables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(missingTables));
        
        string IMigrationMetadata.Id
        {
            get { return "201808061313242_missingTables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
